# -*- coding: utf-8 -*-
"""Ejercicio9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GixzZpmGE7UlNVzzTr5n8Zi-AERKUnmJ
"""

red_ocho_nodos = {
    1: [2, 3],  # El Nodo 1 apunta (se comunica) al 2 y al 3
    2: [3, 4],  # El Nodo 2 apunta al 3 y al 4
    3: [4, 5],  # El Nodo 3 apunta al 4 y al 5
    4: [5, 6],  # El Nodo 4 apunta al 5 y al 6
    5: [6, 7],  # El Nodo 5 apunta al 6 y al 7
    6: [7, 8],  # El Nodo 6 apunta al 7 y al 8
    7: [8, 1],  # El Nodo 7 apunta al 8 y pega la vuelta hacia el 1
    8: [1, 2]   # El Nodo 8 apunta al 1 y al 2, cerrando el ciclo
}

# Imprimimos un título en la consola para que quede ordenado
print("--- Red de Comunicación Dirigida (8 Nodos) ---")

# Iniciamos un ciclo 'for' para recorrer el diccionario.
# La función '.items()' agarra cada línea de arriba y la separa en dos variables: 'nodo' y 'conexiones'
for nodo, conexiones in red_ocho_nodos.items():

    # Imprimimos el resultado usando una f-string (poniendo una 'f' antes de las comillas).
    # Esto nos permite meter las variables directamente adentro de las llaves { }
    print(f"El Nodo {nodo} envía datos directamente a los nodos: {conexiones}")